CREATE TABLE payments (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_code     VARCHAR2(50) UNIQUE NOT NULL,
    invoice_id       NUMBER NOT NULL REFERENCES invoices(id),
    customer_id      NUMBER NOT NULL REFERENCES customers(id),
    account_id       NUMBER NOT NULL REFERENCES accounts(id),
    pay_date         DATE NOT NULL,
    amount           NUMBER(16,2) NOT NULL,
    currency         VARCHAR2(10) NOT NULL,
    category         VARCHAR2(150),
    payer            VARCHAR2(200),
    payment_method   VARCHAR2(100),
    reference_no     VARCHAR2(150),
    description      VARCHAR2(1000),
    notes            VARCHAR2(2000),
    deposit_id       NUMBER,
    created_by       NUMBER,
    created_at       TIMESTAMP NOT NULL
);
COMMIT;
