CREATE TABLE transfers (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_code    VARCHAR2(50) UNIQUE NOT NULL,
    from_account_id  NUMBER NOT NULL REFERENCES accounts(id),
    to_account_id    NUMBER NOT NULL REFERENCES accounts(id),
    xfer_date        DATE NOT NULL,
    description      VARCHAR2(1000),
    currency         VARCHAR2(10) NOT NULL,
    amount           NUMBER(16,2) NOT NULL,
    tags             VARCHAR2(500),
    payment_method   VARCHAR2(100),
    reference_no     VARCHAR2(150),
    created_by       NUMBER,
    created_at       TIMESTAMP NOT NULL
);

INSERT INTO scopes (name) VALUES ('VIEW_TRANSFER');
INSERT INTO scopes (name) VALUES ('CREATE_TRANSFER');

INSERT INTO role_scopes (role_id, scope_id) SELECT r.id, s.id FROM roles r, scopes s WHERE r.role_name = 'SUPER_ADMIN' AND s.name IN ('VIEW_TRANSFER','CREATE_TRANSFER');
INSERT INTO role_scopes (role_id, scope_id) SELECT r.id, s.id FROM roles r, scopes s WHERE r.role_name = 'ACCOUNTANT' AND s.name IN ('VIEW_TRANSFER','CREATE_TRANSFER');
INSERT INTO role_scopes (role_id, scope_id) SELECT r.id, s.id FROM roles r, scopes s WHERE r.role_name = 'VIEWER' AND s.name IN ('VIEW_TRANSFER');

COMMIT;
