package com.bizmotion.rbca.security;
public enum ScopeEnum {
    CREATE_USER, EDIT_USER, DELETE_USER, VIEW_USER, ASSIGN_ROLE,
    CREATE_INVOICE, EDIT_INVOICE, DELETE_INVOICE, VIEW_INVOICE, APPROVE_INVOICE,
    CREATE_PAYMENT, VIEW_PAYMENT, PROCESS_PAYMENT, REFUND_PAYMENT,
    VIEW_LEDGER, POST_JOURNAL_ENTRY, CLOSE_PERIOD,
    VIEW_REPORT, EXPORT_REPORT, GENERATE_REPORT,
    CREATE_CUSTOMER, EDIT_CUSTOMER, VIEW_CUSTOMER, DELETE_CUSTOMER,
    VIEW_AUDIT_LOG, MANAGE_SETTINGS
}
