-- Grant all customer scopes to ADMIN role
INSERT INTO role_scopes (role_id, scope_id)
SELECT r.id, s.id 
FROM roles r 
CROSS JOIN scopes s
WHERE r.role_name = 'ADMIN'
AND s.name IN (
    'VIEW_CUSTOMER','CREATE_CUSTOMER','EDIT_CUSTOMER','DELETE_CUSTOMER',
    'VIEW_INVOICE','CREATE_INVOICE','EDIT_INVOICE','DELETE_INVOICE','APPROVE_INVOICE',
    'VIEW_PAYMENT','CREATE_PAYMENT','PROCESS_PAYMENT','REFUND_PAYMENT',
    'VIEW_LEDGER','POST_JOURNAL_ENTRY','CLOSE_PERIOD',
    'VIEW_REPORT','EXPORT_REPORT','GENERATE_REPORT',
    'VIEW_USER','EDIT_USER','DELETE_USER','ASSIGN_ROLE',
    'VIEW_AUDIT_LOG'
)
AND NOT EXISTS (
    SELECT 1 FROM role_scopes rs 
    WHERE rs.role_id = r.id AND rs.scope_id = s.id
);
COMMIT;
EXIT;